### ISSUE TITLE
Option to disable onTap behaviour

### ISSUE THREAD

**Issue by felixriehm** [DevNico/flutter_breadcrumbs#1]
Hey DevNico, this is a really cool flutter package. Maybe you could add an option to disable the onTap behaviour of the widget. In my project i tried to put the breadcrumb inside a button. I didnt want the 'expand' behaviour so i wrapped it with another GestureDetector (HitTestBehavior.opaque) but it still triggered the breadcrumb GestureDetector. At the end i had to wrap it with 

```
Listener(
      behavior: HitTestBehavior.opaque,
      onPointerDown: ...
      ...
)
```

Apperently this is faster https://stackoverflow.com/questions/53063021/flutter-tap-delay-with-gesturedetector-in-a-tile-of-a-gridview/53063398#53063398.

Cheers!

**Comment by DevNico** [comment]
Added an option to disable the expansion behaviour in [v0.1.0](https://github.com/DevNico/flutter_breadcrumbs/releases/tag/v0.1.0) see https://pub.dev/packages/breadcrumbs
